(() => {
'use strict';
const DB='snapsplit-db',DBV=1,KEY='snapsplit-current-split-id';
const STEPS=['scan','review','people','assign','settle'];
const STEP_LABELS=['Scan','Review','People','Assign','Settle'];
const COLORS=['#4f7cff','#ff7a59','#8a5cf6','#12b886','#ef476f','#ffa62b','#06b6d4','#7f8c8d'];
const FIXTURES=[['Simple diner','./fixtures/simple-diner.txt'],['Family style','./fixtures/family-style.txt'],['Weighted party','./fixtures/weighted-party.txt']];
const DEBUG=new URLSearchParams(location.search).get('debug')==='1';
let dbp,srcImg,ocrWorker,autoSave=0,objUrl='',qrLoaded=false,PeerAPI=null,peer=null,conn=null,roomCrypto=null;
const $=id=>document.getElementById(id);
const refs={nav:$('stepNav'),preview:$('previewCanvas'),ocrText:$('ocrText'),ocrStatus:$('ocrStatus'),ocrBar:$('ocrBar'),imageMeta:$('imageMeta'),hashMeta:$('hashMeta'),processingMeta:$('processingMeta'),duplicate:$('duplicateBanner'),items:$('itemsBody'),validation:$('validationCard'),recent:$('recentPeople'),people:$('peopleList'),assign:$('assignList'),bulk:$('bulkPeopleInput'),receiptSummary:$('receiptSummary'),results:$('resultsList'),settlements:$('settlementList'),audit:$('auditList'),history:$('historyList'),ledger:$('ledgerList'),fixtures:$('fixtureRow'),sticky:$('stickyText'),live:$('liveRegion'),qr:$('qrCanvas'),debugPanel:$('debugPanel'),debugResults:$('debugResults'),roomStatus:$('roomStatus')};
const state={step:'scan',claimMode:false,history:[],ledgers:[],ocr:{status:'Ready.',progress:0,running:false},settings:{cloudEnabled:false,recentPeople:[],license:{key:'',valid:false,plan:'free'}},undo:[],redo:[],duplicate:null,split:emptySplit()};
init().catch(e=>{console.error(e);setOcr(e.message,0,false);announce('SnapSplit failed to initialize.');});

function emptySplit(){return{ id:crypto.randomUUID(), createdAt:iso(), updatedAt:iso(), title:'Untitled split', imageHash:'', imageInfo:{name:'',size:0,preview:''}, imageEdits:{rotation:0,contrast:15,threshold:0,grayscale:true,cropLeft:0,cropRight:0,cropTop:0,cropBottom:0}, receipt:{merchant:'',date:'',currency:'USD',rawText:'',items:[],subtotalCents:0,discountsCents:0,taxCents:0,tipCents:0,totalCents:0,discrepancyCents:0,note:'',taxMode:'taxable',tipMode:'subtotal'}, participants:[], ui:{ack:false}, completed:false};}
function emptyItem(){return{ id:crypto.randomUUID(), name:'New item', quantity:1, unitPriceCents:0, totalPriceCents:0, confidence:.5, sourceText:'', taxable:true, tippable:true, nonSplittable:false, splitMode:'single', assignedParticipantIds:[], customPercentShares:{}, customAmountShares:{}};}
function participant(name,color=COLORS[state.split.participants.length%COLORS.length],weight=1){return{ id:crypto.randomUUID(), name, initials:initials(name), color, weight:Number(weight)||1, isPayer:false, excludeTax:false, excludeTip:false, paymentHandle:''};}
function iso(){return new Date().toISOString();}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0].toUpperCase()).join('')||'?';}
function announce(msg){refs.live.textContent='';setTimeout(()=>refs.live.textContent=msg,20);}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function c2i(c){return (Number(c||0)/100).toFixed(2);}
function parseNum(v){return Number(String(v||'').replace(',','.'))||0;}
function cents(v){if(typeof v==='number')return Math.round(v);const s=String(v||'').trim().replace(/[^0-9,.-]/g,'').replace(/,(?=\d{3}(?:\D|$))/g,'').replace(',', '.');const n=Number(s);return Number.isFinite(n)?Math.round(n*100):0;}
function money(c,curr='USD'){const n=Number(c||0)/100;try{return new Intl.NumberFormat(undefined,{style:'currency',currency:curr}).format(n);}catch{return `${curr} ${n.toFixed(2)}`;}}
function byId(arr,id){return arr.find(x=>x.id===id);} function sum(arr,fn){return arr.reduce((a,x)=>a+fn(x),0);} function last(a){return a[a.length-1]||0;}
function clone(v){return structuredClone(v);} function fmtBytes(b){if(!b)return'0 B';const u=['B','KB','MB'];const p=Math.min(u.length-1,Math.floor(Math.log(b)/Math.log(1024)));return`${(b/(1024**p)).toFixed(p?1:0)} ${u[p]}`;}
function activeIndex(){return STEPS.indexOf(state.step);} function receiptSubtotal(items){return sum(items.filter(i=>!i.nonSplittable),i=>i.totalPriceCents);} 

async function init(){refs.debugPanel.classList.toggle('hidden',!DEBUG); bind(); await Promise.all([loadSettings(),loadHistory(),loadLedgers()]); renderFixtures(); await restoreLatest(); renderAll(); registerSW(); if(DEBUG)runDebug();}
function bind(){
 $('pickBtn').onclick=()=>$('fileInput').click(); $('cameraBtn').onclick=()=>$('cameraInput').click(); $('fileInput').onchange=e=>handleFile(e.target.files?.[0]); $('cameraInput').onchange=e=>handleFile(e.target.files?.[0]); $('pasteBtn').onclick=pasteImage; window.addEventListener('paste',onPaste);
 const dz=$('dropzone'); ['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('drag');})); ['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('drag');if(t==='drop')handleFile(e.dataTransfer.files?.[0]);})); dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('fileInput').click();};
 ['contrastInput','thresholdInput','cropLeftInput','cropRightInput','cropTopInput','cropBottomInput'].forEach(id=>$(id).oninput=e=>{state.split.imageEdits[id.replace('Input','')]=Number(e.target.value);updatePreview();queueSave();});
 $('grayscaleInput').onchange=e=>{state.split.imageEdits.grayscale=e.target.checked;updatePreview();queueSave();}; $('rotateLeftBtn').onclick=()=>rotate(-90); $('rotateRightBtn').onclick=()=>rotate(90);
 $('ocrBtn').onclick=runOCR; $('parseBtn').onclick=()=>applyParsed(parseReceiptText(refs.ocrText.value),true); $('cloudBtn').onclick=cloudParse;
 $('undoBtn').onclick=undo; $('redoBtn').onclick=redo; $('mergeBtn').onclick=mergeDuplicates; $('addItemBtn').onclick=()=>mutate(s=>s.receipt.items.push(emptyItem()));
 ['merchantInput','dateInput','currencyInput','subtotalInput','discountsInput','taxInput','tipInput','totalInput','noteInput'].forEach(id=>$(id).oninput=syncReview); $('ackInput').onchange=e=>{state.split.ui.ack=e.target.checked;queueSave();renderValidation();};
 $('addPersonBtn').onclick=addPerson; $('firstPayerBtn').onclick=()=>mutate(s=>s.participants.forEach((p,i)=>p.isPayer=i===0)); $('personNameInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addPerson();}};
 $('claimModeBtn').onclick=()=>{state.claimMode=!state.claimMode;renderAssign();}; $('bulkAssignBtn').onclick=bulkAssign; $('taxModeInput').onchange=e=>{state.split.receipt.taxMode=e.target.value;renderSettle();queueSave();}; $('tipModeInput').onchange=e=>{state.split.receipt.tipMode=e.target.value;renderSettle();queueSave();};
 $('copySummaryBtn').onclick=()=>copy(buildMarkdown()); $('shareBtn').onclick=shareSummary; $('copyOneBtn').onclick=copyFirst; $('mdBtn').onclick=()=>download(`${fileBase()}.md`,'text/markdown',buildMarkdown()); $('jsonBtn').onclick=()=>download(`${fileBase()}.json`,'application/json',JSON.stringify(exportPayload(),null,2)); $('printBtn').onclick=()=>print(); $('qrBtn').onclick=makeQR; $('saveLedgerBtn').onclick=saveToLedger;
 $('licenseBtn').onclick=validateLicenseFlow; $('backupBtn').onclick=exportBackup; $('restoreBackupBtn').onclick=()=>$('backupFileInput').click(); $('backupFileInput').onchange=importBackup; $('hostRoomBtn').onclick=hostRoom; $('joinRoomBtn').onclick=joinRoom; $('syncRoomBtn').onclick=syncRoom;
 $('historySearchInput').oninput=renderHistory; $('newSplitBtn').onclick=()=>resetSplit(true); $('clearDataBtn').onclick=clearAll; $('debugBtn').onclick=runDebug; $('prevBtn').onclick=()=>goto(activeIndex()-1); $('nextBtn').onclick=()=>goto(activeIndex()+1);
 document.addEventListener('click',clickDelegate); document.addEventListener('input',inputDelegate); window.addEventListener('beforeunload',flushSave);
}
function clickDelegate(e){const b=e.target.closest('[data-action]'); if(!b)return; const {action,id,pid,file,mode}=b.dataset;
 if(action==='step')goto(STEPS.indexOf(id)); else if(action==='fixture')loadFixture(file); else if(action==='load')loadSplit(id); else if(action==='duplicate')duplicateSplit(id); else if(action==='delete')deleteSplit(id); else if(action==='ledger-delete')deleteLedger(id); else if(action==='recent')addRecent(id); else if(action==='remove-person')removePerson(id); else if(action==='toggle-claim')toggleClaim(id,pid); else if(action==='item-del')mutate(s=>s.receipt.items=s.receipt.items.filter(x=>x.id!==id)); else if(action==='item-dup')mutate(s=>{const it=byId(s.receipt.items,id); if(it){const c=clone(it); c.id=crypto.randomUUID(); s.receipt.items.push(c);}}); else if(action==='set-mode')setMode(id,mode); }
function inputDelegate(e){const t=e.target;
 if(t.dataset.itemField)updateItem(t.dataset.id,t.dataset.itemField,t.type==='checkbox'?t.checked:t.value);
 if(t.dataset.personField)updatePerson(t.dataset.id,t.dataset.personField,t.type==='checkbox'?t.checked:t.value);
 if(t.dataset.shareField)updateShare(t.dataset.id,t.dataset.pid,t.dataset.shareField,t.value);
}

async function handleFile(file){if(!file)return; if(!/^image\//.test(file.type||'')&&!/\.(heic|heif)$/i.test(file.name||'')){announce('Choose an image receipt.');return;} if(hasData())resetSplit(false); state.duplicate=null; const ab=await file.arrayBuffer(); state.split.imageHash=await sha(ab); state.split.imageInfo={name:file.name,size:file.size,preview:''}; const dup=state.history.find(h=>h.imageHash&&h.imageHash===state.split.imageHash&&h.id!==state.split.id); if(dup)state.duplicate=dup; if(objUrl)URL.revokeObjectURL(objUrl); objUrl=URL.createObjectURL(file); srcImg=await loadImage(objUrl); state.split.imageInfo.preview=await blobToDataURL(file); await saveImage(state.split.id,file); refs.ocrText.value=''; state.split.receipt.rawText=''; updatePreview(); queueSave(); renderAll(); announce(`Loaded ${file.name}.`);}
function hasData(){const s=state.split; return !!(s.imageHash||s.receipt.rawText||s.receipt.items.length||s.participants.length);} 
async function pasteImage(){try{const items=await navigator.clipboard.read();for(const it of items){const type=it.types.find(t=>t.startsWith('image/')); if(type){const blob=await it.getType(type); await handleFile(new File([blob],`clipboard.${type.split('/')[1]||'png'}`,{type})); return;}}announce('No image in clipboard.');}catch{announce('Clipboard read is blocked.');}}
async function onPaste(e){const f=e.clipboardData?.files?.[0]; if(f){e.preventDefault(); await handleFile(f);}}
function rotate(delta){state.split.imageEdits.rotation=((state.split.imageEdits.rotation+delta)%360+360)%360; updatePreview(); queueSave();}
function processedCanvas(){const img=srcImg; const cvs=document.createElement('canvas'); if(!img){cvs.width=1200;cvs.height=1600; const c=cvs.getContext('2d'); c.fillStyle='#08111f'; c.fillRect(0,0,cvs.width,cvs.height); c.fillStyle='#fff'; c.font='600 26px system-ui'; c.textAlign='center'; c.fillText('Load a receipt to preview it here.',cvs.width/2,cvs.height/2); return {canvas:cvs,meta:'Idle'};} const e=state.split.imageEdits; const scale=Math.min(1,2400/Math.max(img.width,img.height)); const bw=Math.max(1,Math.round(img.width*scale)),bh=Math.max(1,Math.round(img.height*scale)); const base=document.createElement('canvas'); base.width=bw;base.height=bh; const bc=base.getContext('2d',{willReadFrequently:true}); bc.drawImage(img,0,0,bw,bh); const sx=Math.round(bw*e.cropLeft/100), sy=Math.round(bh*e.cropTop/100), sw=Math.max(1,bw-sx-Math.round(bw*e.cropRight/100)), sh=Math.max(1,bh-sy-Math.round(bh*e.cropBottom/100)); const crop=document.createElement('canvas'); crop.width=sw; crop.height=sh; crop.getContext('2d',{willReadFrequently:true}).drawImage(base,sx,sy,sw,sh,0,0,sw,sh); const rot=((e.rotation%360)+360)%360, swap=rot===90||rot===270; cvs.width=swap?crop.height:crop.width; cvs.height=swap?crop.width:crop.height; const c=cvs.getContext('2d',{willReadFrequently:true}); c.save(); c.translate(cvs.width/2,cvs.height/2); c.rotate(rot*Math.PI/180); c.drawImage(crop,-crop.width/2,-crop.height/2); c.restore(); const id=c.getImageData(0,0,cvs.width,cvs.height), d=id.data; const factor=(259*(e.contrast+255))/(255*(259-e.contrast||1)); for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2]; if(e.grayscale){const gray=.2126*r+.7152*g+.0722*b; r=g=b=gray;} r=Math.max(0,Math.min(255,Math.round(factor*(r-128)+128))); g=Math.max(0,Math.min(255,Math.round(factor*(g-128)+128))); b=Math.max(0,Math.min(255,Math.round(factor*(b-128)+128))); if(e.threshold>0){const gray=(r+g+b)/3; r=g=b=gray>=e.threshold?255:0;} d[i]=r; d[i+1]=g; d[i+2]=b;} c.putImageData(id,0,0); return {canvas:cvs,meta:`${rot}° · ${e.grayscale?'gray':'color'}${e.threshold?' · threshold':''}`};}
function updatePreview(){const {canvas,meta}=processedCanvas(); refs.preview.width=canvas.width; refs.preview.height=canvas.height; refs.preview.getContext('2d').drawImage(canvas,0,0); refs.processingMeta.textContent=meta; refs.imageMeta.textContent=state.split.imageInfo.name?`${state.split.imageInfo.name} · ${fmtBytes(state.split.imageInfo.size)}`:'No receipt loaded.'; refs.hashMeta.textContent=state.split.imageHash?`${state.split.imageHash.slice(0,18)}…`:'—';}
async function runOCR(){if(!srcImg){announce('Load an image first.');return;} const blob=await new Promise(r=>processedCanvas().canvas.toBlob(r,'image/png',.92)); const dataUrl=await blobToDataURL(blob); if(!ocrWorker)ocrWorker=makeWorker(); setOcr('Preparing OCR worker…',.03,true); ocrWorker.postMessage({type:'ocr',dataUrl});}
function makeWorker(){const js=`self.onmessage=async e=>{if(e.data.type!=='ocr')return;try{if(!self.Tesseract){self.postMessage({type:'progress',status:'Loading Tesseract.js…',progress:.05});importScripts('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js');}const r=await self.Tesseract.recognize(e.data.dataUrl,'eng',{logger:m=>self.postMessage({type:'progress',status:m.status||'Working…',progress:typeof m.progress==='number'?m.progress:.1})});self.postMessage({type:'done',text:r?.data?.text||'',words:(r?.data?.words||[]).map(w=>({text:w.text,confidence:w.confidence||55}))});}catch(err){self.postMessage({type:'error',message:err.message||String(err)})}}`; const w=new Worker(URL.createObjectURL(new Blob([js],{type:'application/javascript'}))); w.onmessage=e=>{const d=e.data||{}; if(d.type==='progress')setOcr(d.status,d.progress,true); else if(d.type==='done'){refs.ocrText.value=d.text; applyParsed(parseReceiptText(d.text,d.words),true); setOcr('OCR complete.',1,false);} else if(d.type==='error')setOcr(`OCR failed: ${d.message}`,0,false);}; return w;}
function setOcr(status,progress,running){state.ocr={status,progress,running}; refs.ocrStatus.textContent=status; refs.ocrBar.style.width=`${Math.round((progress||0)*100)}%`; announce(status);} 
function parseReceiptText(text,words=[]){const lines=String(text||'').split(/\r?\n/).map(s=>s.trim().replace(/\s+/g,' ')).filter(Boolean); const merchant=lines.find(l=>/[A-Za-z]/.test(l)&&!/^(\d|tel|phone)/i.test(l))||'Unknown merchant'; const dm=String(text).match(/(?:\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})|(?:\d{4}[\/.-]\d{1,2}[\/.-]\d{1,2})/); const date=dm?normDate(dm[0]):''; const currency=/€/u.test(text)?'EUR':/£/u.test(text)?'GBP':/\bCAD\b/i.test(text)?'CAD':'USD'; let subtotal=0,discounts=0,tax=0,tip=0,total=0,carry=''; const items=[]; const skip=/visa|mastercard|amex|cash|change|tender|phone|tel|server|table|guest|receipt|order|auth|approval|invoice|www\.|http|balance/i;
 for(const line of lines){const amounts=moneyTokens(line); if(/sub\s*total/i.test(line)&&amounts.length){subtotal=last(amounts);continue;} if(/tax|vat/i.test(line)&&amounts.length){tax+=last(amounts);continue;} if(/tip|gratuity/i.test(line)&&amounts.length){tip+=last(amounts);continue;} if(/discount|coupon|promo|savings/i.test(line)&&amounts.length){discounts+=amounts.reduce((a,v)=>a+Math.abs(v),0);continue;} if(/(^|\s)total(\s|$)/i.test(line)&&amounts.length){total=Math.max(total,last(amounts));continue;} if(skip.test(line)&&amounts.length)continue; if(!amounts.length){if(!skip.test(line)&&line.length<56)carry=carry?`${carry} ${line}`:line; continue;} const item=parseItem(line,carry,words); carry=''; if(item&&!skip.test(item.name))items.push(item);} if(!subtotal)subtotal=receiptSubtotal(items); if(!total)total=Math.max(0,subtotal-discounts+tax+tip); const discrepancy=subtotal-receiptSubtotal(items); return {merchant,date,currency,items,subtotalCents:subtotal,discountsCents:discounts,taxCents:tax,tipCents:tip,totalCents:total,discrepancyCents:discrepancy};}
function parseItem(line,prefix,words){const amounts=moneyTokens(line); if(!amounts.length)return null; const total=last(amounts); const qm=line.match(/(^|\s)(\d+(?:[.,]\d+)?)\s*(?:x|×|@)\s*(\d+[.,]\d{2})/i); const qty=qm?parseNum(qm[2]):1; const unit=qm?cents(qm[3]):Math.round(total/Math.max(qty,1)); let name=line.replace(/-?(?:\d{1,4}(?:[.,]\d{2})|\d{1,3}(?:[.,]\d{3})+[.,]\d{2})\s*$/,'').replace(/\d+(?:[.,]\d+)?\s*(?:x|×|@)\s*\d+[.,]\d{2}/i,'').trim(); if(prefix)name=`${prefix} ${name}`.trim(); if(!name)name='Receipt item'; let conf=qm?.78:.62; if(name.length>36)conf-=.08; const hit=words.filter(w=>line.includes(w.text||'')).slice(0,5); if(hit.length)conf=(conf+hit.reduce((a,w)=>a+((w.confidence||55)/100),0)/hit.length)/2; return {...emptyItem(),name,quantity:qty,unitPriceCents:unit,totalPriceCents:total,confidence:Math.max(.2,Math.min(.99,conf)),sourceText:line};}
function moneyTokens(line){return [...String(line).matchAll(/-?(?:\d{1,4}(?:[.,]\d{2})|\d{1,3}(?:[.,]\d{3})+[.,]\d{2})/g)].map(m=>cents(m[0])).filter(Number.isFinite);} 
function normDate(s){if(/^\d{4}[\/.-]\d{1,2}[\/.-]\d{1,2}$/.test(s))return s.replace(/[/.]/g,'-'); const p=s.split(/[\/.-]/); if(p.length===3){const y=p[2].length===2?`20${p[2]}`:p[2]; return `${y}-${p[0].padStart(2,'0')}-${p[1].padStart(2,'0')}`;} return s;}
function applyParsed(p,jump){mutate(s=>{s.receipt.rawText=refs.ocrText.value; s.receipt.merchant=p.merchant; s.receipt.date=p.date; s.receipt.currency=p.currency; s.receipt.items=p.items.length?p.items:s.receipt.items; s.receipt.subtotalCents=p.subtotalCents; s.receipt.discountsCents=p.discountsCents; s.receipt.taxCents=p.taxCents; s.receipt.tipCents=p.tipCents; s.receipt.totalCents=p.totalCents; s.receipt.discrepancyCents=p.discrepancyCents; s.title=p.merchant||s.title; s.ui.ack=false;},false); if(jump)goto(1); renderAll(); queueSave();}
function syncReview(){const r=state.split.receipt; r.merchant=$('merchantInput').value.trim(); r.date=$('dateInput').value.trim(); r.currency=($('currencyInput').value.trim()||'USD').toUpperCase(); r.subtotalCents=cents($('subtotalInput').value); r.discountsCents=Math.abs(cents($('discountsInput').value)); r.taxCents=cents($('taxInput').value); r.tipCents=cents($('tipInput').value); r.totalCents=cents($('totalInput').value); r.note=$('noteInput').value; r.discrepancyCents=r.subtotalCents-receiptSubtotal(r.items); state.split.updatedAt=iso(); renderValidation(); renderAssign(); renderSettle(); queueSave();}
function mutate(fn,render=true){state.undo.push(clone(state.split)); if(state.undo.length>50)state.undo.shift(); state.redo=[]; fn(state.split); state.split.updatedAt=iso(); if(render)renderAll(); queueSave(); if(conn?.open&&state.step==='settle')syncRoom().catch(console.error);} 
function undo(){if(!state.undo.length)return; state.redo.push(clone(state.split)); state.split=state.undo.pop(); restoreImageFromState().then(renderAll);} 
function redo(){if(!state.redo.length)return; state.undo.push(clone(state.split)); state.split=state.redo.pop(); restoreImageFromState().then(renderAll);} 
function addPerson(){const name=$('personNameInput').value.trim(); if(!name)return; if(!state.settings.license.valid&&state.split.participants.length>=8){announce('Free mode supports up to eight participants.');return;} mutate(s=>{const p=participant(name,$('personColorInput').value,parseNum($('personWeightInput').value||1)); if(!s.participants.length)p.isPayer=true; s.participants.push(p);}); rememberRecent(name,$('personColorInput').value); $('personNameInput').value=''; $('personWeightInput').value='1';}
function rememberRecent(name,color){const ex=state.settings.recentPeople.find(p=>p.name.toLowerCase()===name.toLowerCase()); if(ex)ex.color=color; else state.settings.recentPeople.unshift({id:crypto.randomUUID(),name,color}); state.settings.recentPeople=state.settings.recentPeople.slice(0,12); saveSettings(); renderPeople();}
function addRecent(id){const p=state.settings.recentPeople.find(x=>x.id===id); if(!p)return; if(!state.settings.license.valid&&state.split.participants.length>=8){announce('Free mode supports up to eight participants.');return;} mutate(s=>s.participants.push(participant(p.name,p.color,1)));}
function removePerson(id){mutate(s=>{s.participants=s.participants.filter(p=>p.id!==id); s.receipt.items.forEach(it=>{it.assignedParticipantIds=it.assignedParticipantIds.filter(x=>x!==id); delete it.customPercentShares[id]; delete it.customAmountShares[id];}); if(!s.participants.some(p=>p.isPayer)&&s.participants[0])s.participants[0].isPayer=true;});}
function updatePerson(id,field,val){mutate(s=>{const p=byId(s.participants,id); if(!p)return; if(field==='name'||field==='color'||field==='paymentHandle')p[field]=val; if(field==='weight')p.weight=Math.max(0,parseNum(val)||0); if(field==='isPayer')s.participants.forEach(x=>x.isPayer=x.id===id); if(field==='excludeTax'||field==='excludeTip')p[field]=!!val;});}
function updateItem(id,field,val){mutate(s=>{const it=byId(s.receipt.items,id); if(!it)return; if(field==='name')it.name=val; if(field==='quantity')it.quantity=Math.max(0,parseNum(val)||0); if(field==='unitPriceCents')it.unitPriceCents=cents(val); if(field==='totalPriceCents')it.totalPriceCents=cents(val); if(field==='confidence')it.confidence=Math.max(0,Math.min(.99,Number(val))); if(field==='taxable'||field==='tippable'||field==='nonSplittable')it[field]=!!val; if((field==='quantity'||field==='unitPriceCents')&&it.quantity)it.totalPriceCents=Math.round(it.quantity*it.unitPriceCents); s.receipt.discrepancyCents=s.receipt.subtotalCents-receiptSubtotal(s.receipt.items);});}
function updateShare(id,pid,field,val){mutate(s=>{const it=byId(s.receipt.items,id); if(!it)return; if(field==='percent')it.customPercentShares[pid]=Number(val||0); if(field==='amount')it.customAmountShares[pid]=cents(val||0);});}
function toggleClaim(id,pid){mutate(s=>{const it=byId(s.receipt.items,id); if(!it||it.nonSplittable)return; const on=it.assignedParticipantIds.includes(pid); it.assignedParticipantIds=on?it.assignedParticipantIds.filter(x=>x!==pid):[...it.assignedParticipantIds,pid]; if(it.splitMode==='single'&&it.assignedParticipantIds.length>1)it.splitMode='equal'; if(it.assignedParticipantIds.length===0)delete it.customPercentShares[pid];});}
function setMode(id,mode){mutate(s=>{const it=byId(s.receipt.items,id); if(!it)return; it.splitMode=mode; if(!it.assignedParticipantIds.length&&s.participants[0])it.assignedParticipantIds=[s.participants[0].id];});}
function mergeDuplicates(){mutate(s=>{const map=new Map(); for(const it of s.receipt.items){const k=`${it.name.trim().toLowerCase()}::${it.unitPriceCents}::${it.nonSplittable}`; if(!map.has(k))map.set(k,clone(it)); else {const m=map.get(k); m.quantity+=it.quantity; m.totalPriceCents+=it.totalPriceCents; m.confidence=Math.min(m.confidence,it.confidence);}} s.receipt.items=[...map.values()]; s.receipt.discrepancyCents=s.receipt.subtotalCents-receiptSubtotal(s.receipt.items);});}
function bulkAssign(){const ids=[...refs.bulk.selectedOptions].map(o=>o.value); if(!ids.length){announce('Select one or more participants first.');return;} mutate(s=>s.receipt.items.forEach(it=>{if(!it.nonSplittable&&!it.assignedParticipantIds.length){it.assignedParticipantIds=[...ids]; it.splitMode=ids.length===1?'single':'equal';}}));}
function goto(i){i=Math.max(0,Math.min(STEPS.length-1,i)); const next=STEPS[i]; if(next!=='scan'&&state.split.receipt.discrepancyCents!==0&&!state.split.ui.ack&&i>1){state.step='review'; announce('Acknowledge the discrepancy before continuing.');} else state.step=next; renderAll(); queueSave();}

function renderAll(){renderNav(); renderSections(); renderReview(); renderPeople(); renderAssign(); renderSettle(); renderHistory(); renderLedgers(); renderSticky(); renderDuplicate(); updatePreview(); $('licenseStatus').textContent=`Plan: ${state.settings.license.plan}. Premium features ${state.settings.license.valid?'enabled.':'stay disabled until a real license provider is connected.'}`;}
function renderNav(){refs.nav.innerHTML=STEPS.map((s,i)=>`<button class="step-pill ${s===state.step?'active':''} ${i<activeIndex()?'done':''}" data-action="step" data-id="${s}"><span>${i+1}</span><span>${STEP_LABELS[i]}</span></button>`).join('');}
function renderSections(){for(const s of STEPS)$(`${s}Section`).classList.toggle('hidden',s!==state.step); $('taxModeInput').value=state.split.receipt.taxMode||'taxable'; $('tipModeInput').value=state.split.receipt.tipMode||'subtotal'; $('licenseInput').value=state.settings.license.key||'';}
function renderDuplicate(){if(!state.duplicate){refs.duplicate.classList.add('hidden'); refs.duplicate.textContent=''; return;} refs.duplicate.classList.remove('hidden'); refs.duplicate.textContent=`Possible duplicate found: ${state.duplicate.receipt?.merchant||'Saved split'} (${state.duplicate.receipt?.date||'unknown date'}).`;}
function renderReview(){const r=state.split.receipt; $('merchantInput').value=r.merchant||''; $('dateInput').value=r.date||''; $('currencyInput').value=r.currency||'USD'; $('subtotalInput').value=c2i(r.subtotalCents); $('discountsInput').value=c2i(r.discountsCents); $('taxInput').value=c2i(r.taxCents); $('tipInput').value=c2i(r.tipCents); $('totalInput').value=c2i(r.totalCents); $('noteInput').value=r.note||''; $('ackInput').checked=!!state.split.ui.ack; renderValidation(); refs.items.innerHTML=r.items.map(it=>`<tr><td><input data-id="${it.id}" data-item-field="name" value="${esc(it.name)}"></td><td><input data-id="${it.id}" data-item-field="quantity" value="${esc(String(it.quantity))}"></td><td><input data-id="${it.id}" data-item-field="unitPriceCents" value="${c2i(it.unitPriceCents)}"></td><td><input data-id="${it.id}" data-item-field="totalPriceCents" value="${c2i(it.totalPriceCents)}"></td><td><div class="tag ${it.confidence<.6?'warn-text':''}">${Math.round(it.confidence*100)}%</div><input data-id="${it.id}" data-item-field="confidence" type="range" min="0" max="0.99" step="0.01" value="${it.confidence}"></td><td><input data-id="${it.id}" data-item-field="taxable" type="checkbox" ${it.taxable?'checked':''}></td><td><input data-id="${it.id}" data-item-field="tippable" type="checkbox" ${it.tippable?'checked':''}></td><td><input data-id="${it.id}" data-item-field="nonSplittable" type="checkbox" ${it.nonSplittable?'checked':''}></td><td><div class="row wrap"><button class="secondary" data-action="item-dup" data-id="${it.id}" type="button">Duplicate</button><button class="ghost" data-action="item-del" data-id="${it.id}" type="button">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="9" class="muted">No items yet.</td></tr>';}
function renderValidation(){const r=state.split.receipt, comp=receiptSubtotal(r.items), diff=r.subtotalCents-comp, issues=[]; if(diff)issues.push(`<div class="banner warn">Computed items differ from extracted subtotal by <strong>${money(diff,r.currency)}</strong>.</div>`); if(!r.totalCents)issues.push('<div class="banner warn">Receipt total is missing and should be confirmed.</div>'); if(r.items.some(i=>i.confidence<.6))issues.push('<div class="banner warn">One or more items have low confidence.</div>'); refs.validation.innerHTML=`<div class="row wrap"><div><h3>Validation</h3><div class="muted">Review every highlighted field before continuing.</div></div><span class="tag ${diff===0?'ok':'warn-text'}">${diff===0?'Balanced':'Needs review'}</span></div><div class="summary-grid"><div class="metric"><span>Extracted subtotal</span><strong>${money(r.subtotalCents,r.currency)}</strong></div><div class="metric"><span>Computed items</span><strong>${money(comp,r.currency)}</strong></div><div class="metric"><span>Difference</span><strong class="${diff===0?'ok':'warn-text'}">${money(diff,r.currency)}</strong></div><div class="metric"><span>Receipt total</span><strong>${money(r.totalCents||r.subtotalCents-r.discountsCents+r.taxCents+r.tipCents,r.currency)}</strong></div></div>${issues.join('')||'<div class="banner">No major issues detected. You can still edit everything inline.</div>'}`;}
function renderPeople(){refs.recent.innerHTML=state.settings.recentPeople.map(p=>`<button class="chip" data-action="recent" data-id="${p.id}" type="button"><span style="inline-size:10px;block-size:10px;border-radius:999px;background:${p.color};display:inline-block"></span>${esc(p.name)}</button>`).join('')||'<span class="muted">Recent people appear here after you add them.</span>'; refs.people.innerHTML=state.split.participants.map(p=>`<div class="person-card"><div class="row wrap"><div class="row"><div class="avatar" style="background:${p.color}">${esc(p.initials)}</div><div><strong>${esc(p.name)}</strong><div class="muted">${p.isPayer?'Paid the bill':'Pays their share'} · weight ${p.weight}</div></div></div><button class="ghost" data-action="remove-person" data-id="${p.id}" type="button">Remove</button></div><div class="grid two"><label>Name<input data-id="${p.id}" data-person-field="name" value="${esc(p.name)}"></label><label>Color<input data-id="${p.id}" data-person-field="color" type="color" value="${p.color}"></label><label>Weight<input data-id="${p.id}" data-person-field="weight" type="number" min="0" step="0.1" value="${p.weight}"></label><label>Payment handle<input data-id="${p.id}" data-person-field="paymentHandle" placeholder="@handle" value="${esc(p.paymentHandle||'')}"></label></div><div class="row wrap"><label class="check"><input data-id="${p.id}" data-person-field="isPayer" type="checkbox" ${p.isPayer?'checked':''}> Payer</label><label class="check"><input data-id="${p.id}" data-person-field="excludeTax" type="checkbox" ${p.excludeTax?'checked':''}> Exclude tax</label><label class="check"><input data-id="${p.id}" data-person-field="excludeTip" type="checkbox" ${p.excludeTip?'checked':''}> Exclude tip</label></div></div>`).join('')||'<div class="muted">Add at least one participant.</div>';}
function renderAssign(){refs.bulk.innerHTML=state.split.participants.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join(''); refs.assign.innerHTML=state.split.receipt.items.map(it=>{const set=new Set(it.assignedParticipantIds); return `<div class="item-card"><div class="row wrap"><div><strong>${esc(it.name)}</strong><div class="muted">${money(it.totalPriceCents,state.split.receipt.currency)} · qty ${it.quantity}${it.nonSplittable?' · not splittable':''}${it.confidence<.6?' · low confidence':''}</div></div><span class="tag">${Math.round(it.confidence*100)}%</span></div><div class="pill-row">${state.split.participants.map(p=>`<button class="chip ${set.has(p.id)?'active':''}" data-action="toggle-claim" data-id="${it.id}" data-pid="${p.id}" type="button" ${it.nonSplittable?'disabled':''}><span style="inline-size:10px;block-size:10px;border-radius:999px;background:${p.color};display:inline-block"></span>${esc(p.name)}</button>`).join('')||'<span class="muted">Add participants first.</span>'}</div><div class="grid two"><label>Split mode<select data-mode-id="${it.id}"><option ${it.splitMode==='single'?'selected':''} value="single">Single</option><option ${it.splitMode==='equal'?'selected':''} value="equal">Equal</option><option ${it.splitMode==='weighted'?'selected':''} value="weighted">Weighted</option><option ${it.splitMode==='percent'?'selected':''} value="percent">Percent</option><option ${it.splitMode==='fixed'?'selected':''} value="fixed">Fixed amount</option></select></label><div class="row wrap"><label class="check"><input data-id="${it.id}" data-item-field="taxable" type="checkbox" ${it.taxable?'checked':''}> Taxable</label><label class="check"><input data-id="${it.id}" data-item-field="tippable" type="checkbox" ${it.tippable?'checked':''}> Tippable</label><label class="check"><input data-id="${it.id}" data-item-field="nonSplittable" type="checkbox" ${it.nonSplittable?'checked':''}> Skip</label></div></div>${customShareUI(it)}</div>`;}).join('')||'<div class="muted">No items to assign yet.</div>'; refs.assign.querySelectorAll('select[data-mode-id]').forEach(sel=>sel.onchange=e=>setMode(e.target.dataset.modeId,e.target.value));}
function customShareUI(it){if(!['percent','fixed'].includes(it.splitMode))return''; return `<div class="grid two">${it.assignedParticipantIds.map(pid=>{const p=byId(state.split.participants,pid); if(!p)return''; return `<label>${esc(p.name)} ${it.splitMode==='percent'?'%':'amount'}<input data-id="${it.id}" data-pid="${pid}" data-share-field="${it.splitMode==='percent'?'percent':'amount'}" value="${it.splitMode==='percent'?esc(String(it.customPercentShares[pid]??'')):c2i(it.customAmountShares[pid]??0)}"></label>`;}).join('')}</div>`;}
function calc(split){const people={}; const plist=split.participants; const pmap=new Map(plist.map(p=>[p.id,p])); plist.forEach(p=>people[p.id]={id:p.id,name:p.name,color:p.color,isPayer:p.isPayer,paymentHandle:p.paymentHandle||'',items:[],itemSubtotalCents:0,taxableSubtotalCents:0,tippableSubtotalCents:0,taxShareCents:0,tipShareCents:0,discountShareCents:0,finalCents:0}); const out={people,settlements:[],audit:[],errors:[],valid:true,totals:{items:0,tax:0,tip:0,discounts:0,final:0}};
 split.receipt.items.filter(i=>!i.nonSplittable).forEach(it=>{const claims=claimShares(it,plist); if(!claims.length){out.valid=false; out.errors.push(`Unclaimed item: ${it.name}`); return;} alloc(it.totalPriceCents,claims).forEach(a=>{const person=people[a.participantId]; if(!person)return; person.items.push({name:it.name,cents:a.cents,ratio:a.ratio}); person.itemSubtotalCents+=a.cents; if(it.taxable&&!pmap.get(a.participantId)?.excludeTax)person.taxableSubtotalCents+=a.cents; if(it.tippable&&!pmap.get(a.participantId)?.excludeTip)person.tippableSubtotalCents+=a.cents; out.totals.items+=a.cents;});});
 alloc(Math.abs(split.receipt.discountsCents||0), plist.map(p=>({participantId:p.id,numerator:Math.max(0,people[p.id].itemSubtotalCents)}))).forEach(a=>{people[a.participantId].discountShareCents+=a.cents; out.totals.discounts+=a.cents;});
 alloc(split.receipt.taxCents||0, plist.map(p=>({participantId:p.id,numerator:split.receipt.taxMode==='equal'?(people[p.id].itemSubtotalCents>0?1:0):people[p.id].taxableSubtotalCents}))).forEach(a=>{people[a.participantId].taxShareCents+=a.cents; out.totals.tax+=a.cents;});
 alloc(split.receipt.tipCents||0, plist.map(p=>({participantId:p.id,numerator:split.receipt.tipMode==='equal'?(people[p.id].itemSubtotalCents>0?1:0):people[p.id].tippableSubtotalCents}))).forEach(a=>{people[a.participantId].tipShareCents+=a.cents; out.totals.tip+=a.cents;});
 plist.forEach(p=>{const person=people[p.id]; person.finalCents=person.itemSubtotalCents+person.taxShareCents+person.tipShareCents-person.discountShareCents; out.totals.final+=person.finalCents;}); const expect=Math.max(0,split.receipt.totalCents||split.receipt.subtotalCents-Math.abs(split.receipt.discountsCents)+split.receipt.taxCents+split.receipt.tipCents); if(out.totals.final!==expect){out.valid=false; out.errors.push(`Allocation mismatch: expected ${money(expect,split.receipt.currency)}, got ${money(out.totals.final,split.receipt.currency)}.`);} if(split.receipt.discrepancyCents!==0){out.valid=false; out.errors.push(`Receipt item subtotal differs from extracted subtotal by ${money(split.receipt.discrepancyCents,split.receipt.currency)}.`);} const payer=plist.find(p=>p.isPayer)||plist[0]; if(payer)out.settlements=plist.filter(p=>p.id!==payer.id&&people[p.id].finalCents>0).map(p=>({from:p.name,to:payer.name,cents:people[p.id].finalCents,handle:people[payer.id]?.paymentHandle||''})); out.audit=[`Items allocated: ${money(out.totals.items,split.receipt.currency)}`,`Discounts allocated: ${money(out.totals.discounts,split.receipt.currency)}`,`Tax allocated: ${money(out.totals.tax,split.receipt.currency)}`,`Tip allocated: ${money(out.totals.tip,split.receipt.currency)}`,`Final allocated total: ${money(out.totals.final,split.receipt.currency)}`]; return out;}
function claimShares(it,plist){const ids=it.assignedParticipantIds.filter(id=>plist.some(p=>p.id===id)); if(!ids.length)return[]; if(it.splitMode==='single')return[{participantId:ids[0],numerator:1}]; if(it.splitMode==='equal')return ids.map(id=>({participantId:id,numerator:1})); if(it.splitMode==='weighted')return ids.map(id=>({participantId:id,numerator:plist.find(p=>p.id===id)?.weight||1})); if(it.splitMode==='percent')return ids.map(id=>({participantId:id,numerator:Number(it.customPercentShares[id]||0)})); if(it.splitMode==='fixed'){const entries=ids.map(id=>({participantId:id,explicitCents:Number(it.customAmountShares[id]||0)})); if(entries.reduce((a,x)=>a+x.explicitCents,0)===it.totalPriceCents)return entries; return ids.map(id=>({participantId:id,numerator:1}));} return ids.map(id=>({participantId:id,numerator:1}));}
function alloc(total,shares){shares=shares.filter(s=>(s.explicitCents||s.numerator||0)>0); if(!shares.length||total===0)return shares.map(s=>({participantId:s.participantId,cents:s.explicitCents||0,ratio:0})); if(shares.every(s=>Number.isFinite(s.explicitCents)))return shares.map(s=>({participantId:s.participantId,cents:s.explicitCents,ratio:total?s.explicitCents/total:0})); const den=shares.reduce((a,s)=>a+Math.max(0,s.numerator),0)||shares.length; const rows=shares.map((s,i)=>{const exact=total*(Math.max(0,s.numerator)/den),floor=Math.floor(exact); return{participantId:s.participantId,cents:floor,remainder:exact-floor,ratio:den?Math.max(0,s.numerator)/den:0,order:i};}); let rem=total-rows.reduce((a,r)=>a+r.cents,0); rows.sort((a,b)=>b.remainder-a.remainder||a.order-b.order); for(let i=0;i<rows.length&&rem>0;i++,rem--)rows[i].cents++; return rows.sort((a,b)=>a.order-b.order).map(r=>({participantId:r.participantId,cents:r.cents,ratio:r.ratio}));}
function renderSettle(){const c=calc(state.split),r=state.split.receipt; refs.receiptSummary.innerHTML=`<div class="row wrap"><div><h3>${esc(r.merchant||'Untitled receipt')}</h3><div class="muted">${esc(r.date||'No date')} · ${esc(r.currency)}</div></div><span class="tag ${c.valid?'ok':'warn-text'}">${c.valid?'Exact':'Review'}</span></div><div class="summary-grid"><div class="metric"><span>Subtotal</span><strong>${money(r.subtotalCents,r.currency)}</strong></div><div class="metric"><span>Discounts</span><strong>-${money(Math.abs(r.discountsCents),r.currency)}</strong></div><div class="metric"><span>Tax</span><strong>${money(r.taxCents,r.currency)}</strong></div><div class="metric"><span>Tip</span><strong>${money(r.tipCents,r.currency)}</strong></div><div class="metric"><span>Total</span><strong>${money(r.totalCents||c.totals.final,r.currency)}</strong></div><div class="metric"><span>Discrepancy</span><strong class="${r.discrepancyCents===0?'ok':'warn-text'}">${money(r.discrepancyCents,r.currency)}</strong></div></div>${c.errors.map(e=>`<div class="banner warn">${esc(e)}</div>`).join('')}`; refs.results.innerHTML=Object.values(c.people).map(p=>`<div class="result-card"><div class="row wrap"><div class="row"><div class="avatar" style="background:${p.color}">${esc(initials(p.name))}</div><div><strong>${esc(p.name)}</strong><div class="muted">${p.isPayer?'Paid the bill':'Owes their share'}</div></div></div><span class="tag">${money(p.finalCents,r.currency)}</span></div><div class="summary-grid"><div class="metric"><span>Items</span><strong>${money(p.itemSubtotalCents,r.currency)}</strong></div><div class="metric"><span>Tax share</span><strong>${money(p.taxShareCents,r.currency)}</strong></div><div class="metric"><span>Tip share</span><strong>${money(p.tipShareCents,r.currency)}</strong></div><div class="metric"><span>Discount share</span><strong>-${money(p.discountShareCents,r.currency)}</strong></div></div><div class="stack">${p.items.map(it=>`<div class="banner"><strong>${esc(it.name)}</strong><div class="muted small">${money(it.cents,r.currency)} · ${Math.round(it.ratio*100)}%</div></div>`).join('')||'<div class="muted">No assigned items.</div>'}</div>${payLinks(p,c)}</div>`).join(''); refs.settlements.innerHTML=c.settlements.map(s=>`<div class="settlement"><div><strong>${esc(s.from)}</strong> pays <strong>${esc(s.to)}</strong></div><div>${money(s.cents,r.currency)}</div></div>`).join('')||'<div class="muted">Settlement instructions appear once there is a payer and owed balances.</div>'; refs.audit.innerHTML=c.audit.map(a=>`<div class="banner">${esc(a)}</div>`).join(''); state.split.completed=c.valid&&state.step==='settle';}
function payLinks(p,c){const payer=Object.values(c.people).find(x=>x.isPayer); if(!payer||p.isPayer||!payer.paymentHandle)return''; const amt=(p.finalCents/100).toFixed(2), note=encodeURIComponent(`${state.split.receipt.merchant||'Receipt'} with SnapSplit`), handle=payer.paymentHandle.replace(/^@/,''); return `<div class="row wrap"><a class="chip" target="_blank" rel="noopener" href="https://venmo.com/${encodeURIComponent(handle)}?txn=pay&amount=${encodeURIComponent(amt)}&note=${note}">Venmo ${esc(payer.paymentHandle)}</a><a class="chip" target="_blank" rel="noopener" href="https://cash.app/$${encodeURIComponent(handle)}/${encodeURIComponent(amt)}">Cash App</a><a class="chip" target="_blank" rel="noopener" href="https://www.paypal.me/${encodeURIComponent(handle)}/${encodeURIComponent(amt)}">PayPal.me</a></div>`;}
function renderHistory(){const q=$('historySearchInput').value.trim().toLowerCase(); const list=state.history.filter(s=>!q||[s.title,s.receipt?.merchant,s.receipt?.date,(s.participants||[]).map(p=>p.name).join(' ')].join(' ').toLowerCase().includes(q)); refs.history.innerHTML=list.map(s=>`<div class="history-card"><div class="row wrap"><div><strong>${esc(s.receipt?.merchant||s.title||'Untitled split')}</strong><div class="muted small">${esc(s.receipt?.date||'No date')} · ${(s.participants||[]).length} people</div></div><span class="tag">${money(s.receipt?.totalCents||0,s.receipt?.currency||'USD')}</span></div><div class="muted small">Updated ${new Date(s.updatedAt).toLocaleString()}</div><div class="row wrap"><button class="secondary" data-action="load" data-id="${s.id}" type="button">Open</button><button class="ghost" data-action="duplicate" data-id="${s.id}" type="button">Duplicate</button><button class="ghost danger" data-action="delete" data-id="${s.id}" type="button">Delete</button></div></div>`).join('')||'<div class="muted">No saved splits yet.</div>';}
function renderLedgers(){refs.ledger.innerHTML=state.ledgers.map(l=>{const s=ledgerSummary(l); return `<div class="history-card"><div class="row wrap"><div><strong>${esc(l.name)}</strong><div class="muted small">${l.receipts.length} receipts · ${esc(l.currency)}</div></div><button class="ghost danger" data-action="ledger-delete" data-id="${l.id}" type="button">Delete</button></div><div class="stack">${s.balances.map(b=>`<div class="banner"><strong>${esc(b.name)}</strong><div class="muted small">${money(b.cents,l.currency)}</div></div>`).join('')}</div><div class="stack">${s.transfers.map(t=>`<div class="settlement"><div>${esc(t.from)} → ${esc(t.to)}</div><div>${money(t.cents,l.currency)}</div></div>`).join('')||'<div class="muted">Everyone is settled.</div>'}</div></div>`;}).join('')||'<div class="muted">No Trip Ledger yet.</div>';}
function renderSticky(){refs.sticky.textContent=`Step ${activeIndex()+1}/5 · ${state.split.receipt.items.length} items · ${state.split.participants.length} people · ${money(state.split.receipt.totalCents||0,state.split.receipt.currency)}`; $('prevBtn').disabled=state.step==='scan'; $('nextBtn').disabled=state.step==='review'&&state.split.receipt.discrepancyCents!==0&&!state.split.ui.ack; $('nextBtn').textContent=state.step==='settle'?'Done':'Continue';}
function renderFixtures(){refs.fixtures.innerHTML=FIXTURES.map(([name,file])=>`<button class="secondary" data-action="fixture" data-file="${file}" type="button">${esc(name)}</button>`).join('');}
async function loadFixture(file){const t=await fetch(file).then(r=>r.text()); refs.ocrText.value=t; applyParsed(parseReceiptText(t),true); announce('Fixture loaded.');}
function fileBase(){return (state.split.receipt.merchant||'snapsplit').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'snapsplit';}
function buildMarkdown(){const c=calc(state.split),r=state.split.receipt,lines=[`# SnapSplit · ${r.merchant||'Receipt'}`,'',`- Date: ${r.date||'Unknown'}`,`- Currency: ${r.currency}`,`- Subtotal: ${money(r.subtotalCents,r.currency)}`,`- Discounts: -${money(Math.abs(r.discountsCents),r.currency)}`,`- Tax: ${money(r.taxCents,r.currency)}`,`- Tip: ${money(r.tipCents,r.currency)}`,`- Total: ${money(r.totalCents,r.currency)}`,`- Discrepancy: ${money(r.discrepancyCents,r.currency)}`,'','## People']; Object.values(c.people).forEach(p=>lines.push(`- **${p.name}** — ${money(p.finalCents,r.currency)} (items ${money(p.itemSubtotalCents,r.currency)}, tax ${money(p.taxShareCents,r.currency)}, tip ${money(p.tipShareCents,r.currency)}, discount -${money(p.discountShareCents,r.currency)})`)); lines.push('','## Settlement'); c.settlements.forEach(s=>lines.push(`- ${s.from} pays ${s.to} ${money(s.cents,r.currency)}`)); if(!c.settlements.length)lines.push('- Already settled.'); return lines.join('\n');}
function exportPayload(){return{version:1,split:state.split,calculation:calc(state.split),tripLedgers:state.ledgers};}
async function copy(text){try{await navigator.clipboard.writeText(text); announce('Copied to clipboard.');}catch{announce('Copy failed.');}}
function download(name,type,text){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a'); a.href=u; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(u),2000);}
async function shareSummary(){const text=buildMarkdown(); if(navigator.share){try{await navigator.share({title:`SnapSplit · ${state.split.receipt.merchant||'Receipt'}`,text}); return;}catch{}} copy(text);} 
function copyFirst(){const c=calc(state.split),p=Object.values(c.people)[0]; if(!p)return; copy(`${p.name} owes ${money(p.finalCents,state.split.receipt.currency)}\n${p.items.map(i=>`${i.name} ${money(i.cents,state.split.receipt.currency)}`).join(', ')}`);} 
async function makeQR(){const payload=JSON.stringify({merchant:state.split.receipt.merchant,date:state.split.receipt.date,total:state.split.receipt.totalCents,currency:state.split.receipt.currency,people:Object.values(calc(state.split).people).map(p=>[p.name,p.finalCents]),settle:calc(state.split).settlements.map(s=>[s.from,s.to,s.cents])}); if(payload.length>900){announce('Summary is too long for a reliable QR code.');return;} if(!qrLoaded){await loadScript('https://cdn.jsdelivr.net/npm/qrcode@1.5.3/build/qrcode.min.js'); qrLoaded=true;} refs.qr.classList.remove('hidden'); window.QRCode.toCanvas(refs.qr,payload,{width:220,margin:1});}
function ledgerSummary(ledger){const bal=new Map(); ledger.participants.forEach(p=>bal.set(p.name,0)); ledger.receipts.forEach(r=>{r.results.forEach(person=>bal.set(person.name,(bal.get(person.name)||0)-person.finalCents)); bal.set(r.payer,(bal.get(r.payer)||0)+r.totalCents);}); const creditors=[...bal.entries()].filter(([,c])=>c>0).sort((a,b)=>b[1]-a[1]); const debtors=[...bal.entries()].filter(([,c])=>c<0).sort((a,b)=>a[1]-b[1]); const transfers=[]; let i=0,j=0; while(i<debtors.length&&j<creditors.length){const d=debtors[i],cr=creditors[j],amt=Math.min(Math.abs(d[1]),cr[1]); if(amt>0)transfers.push({from:d[0],to:cr[0],cents:amt}); d[1]+=amt; cr[1]-=amt; if(d[1]===0)i++; if(cr[1]===0)j++;} return{balances:[...bal.entries()].map(([name,cents])=>({name,cents})),transfers};}
async function saveToLedger(){const c=calc(state.split); if(!c.valid){announce('Fix validation issues before adding this split to Trip Ledger.');return;} const name=$('ledgerNameInput').value.trim()||'Trip Ledger', currency=$('ledgerCurrencyInput').value.trim()||state.split.receipt.currency||'USD'; let ledger=state.ledgers.find(l=>l.name===name&&l.currency===currency); const receipt={id:state.split.id,merchant:state.split.receipt.merchant,date:state.split.receipt.date,totalCents:state.split.receipt.totalCents,payer:state.split.participants.find(p=>p.isPayer)?.name||state.split.participants[0]?.name||'Unknown',results:Object.values(c.people).map(p=>({name:p.name,finalCents:p.finalCents}))}; if(!ledger){ledger={id:crypto.randomUUID(),name,currency,participants:state.split.participants.map(p=>({name:p.name})),receipts:[]}; state.ledgers.unshift(ledger);} ledger.receipts=[...ledger.receipts.filter(r=>r.id!==receipt.id),receipt]; await saveLedgers(); renderLedgers(); announce('Added to Trip Ledger.');}
function deleteLedger(id){state.ledgers=state.ledgers.filter(l=>l.id!==id); saveLedgers().then(renderLedgers);} 
async function validateLicenseFlow(){const key=$('licenseInput').value.trim(); state.settings.license=await validateLicense(key); state.settings.license.key=key; await saveSettings(); renderAll();}
async function validateLicense(key){return{valid:false,plan:'free'};}
async function cloudParse(){if(!srcImg){announce('Load an image first.');return;} if(!confirm('Cloud parsing uploads the processed receipt image to a third-party service when configured. Continue?'))return; state.settings.cloudEnabled=true; await saveSettings(); try{const blob=await new Promise(r=>processedCanvas().canvas.toBlob(r,'image/png',.92)); await parseReceiptWithCloud(blob,{});}catch(e){setOcr(e.message,0,false);}} 
async function parseReceiptWithCloud(imageBlob,config){throw new Error('Cloud parsing is not configured.');}
async function exportBackup(){if(!state.settings.license.valid){announce('Encrypted backup is a premium feature.');return;} const pass=prompt('Enter a passphrase for the encrypted backup.'); if(!pass)return; const payload={version:1,exportedAt:iso(),settings:state.settings,history:state.history,ledgers:state.ledgers}; const data=await encryptJSON(payload,pass); download(`snapsplit-backup-${Date.now()}.json`,'application/json',JSON.stringify(data,null,2));}
async function importBackup(e){const file=e.target.files?.[0]; e.target.value=''; if(!file)return; if(!state.settings.license.valid){announce('Encrypted backup import is a premium feature.');return;} const pass=prompt('Enter the backup passphrase.'); if(!pass)return; try{const data=JSON.parse(await file.text()); const payload=await decryptJSON(data,pass); state.settings=payload.settings||state.settings; state.ledgers=payload.ledgers||[]; for(const split of payload.history||[])await saveSplit(split); await saveLedgers(); await saveSettings(); await loadHistory(); renderAll(); announce('Backup imported.');}catch(err){announce(`Backup import failed: ${err.message}`);}}
async function clearAll(){if(!confirm('Delete every SnapSplit draft, image, history entry, and Trip Ledger from this device?'))return; const db=await openDB(); db.close(); await new Promise((res,rej)=>{const req=indexedDB.deleteDatabase(DB); req.onsuccess=res; req.onerror=()=>rej(req.error);}); dbp=null; state.history=[]; state.ledgers=[]; state.settings.recentPeople=[]; resetSplit(false); await init();}
function resetSplit(render=true){state.split=emptySplit(); state.undo=[]; state.redo=[]; state.duplicate=null; srcImg=null; if(objUrl)URL.revokeObjectURL(objUrl); objUrl=''; refs.ocrText.value=''; localStorage.setItem(KEY,state.split.id); if(render)renderAll(); queueSave();}
function queueSave(){clearTimeout(autoSave); autoSave=setTimeout(()=>saveCurrent().catch(console.error),300);} function flushSave(){if(autoSave){clearTimeout(autoSave); saveCurrent().catch(console.error);}}
async function saveCurrent(){if(!state.settings.license.valid&&state.history.length>=5&&!state.history.some(h=>h.id===state.split.id)){announce('Free mode keeps up to five saved splits. Delete one or add a license for more.');return;} state.split.updatedAt=iso(); await saveSplit(state.split); localStorage.setItem(KEY,state.split.id); await loadHistory(); renderHistory();}
async function restoreLatest(){const id=localStorage.getItem(KEY); const stored=id?await getSplit(id):null; if(stored){state.split=revive(stored); await restoreImageFromState(); return;} if(state.history[0]){state.split=revive(state.history[0]); await restoreImageFromState();}}
function revive(s){const x=clone(s); x.receipt=x.receipt||emptySplit().receipt; x.receipt.items=x.receipt.items||[]; x.participants=x.participants||[]; x.ui=x.ui||{ack:false}; x.imageEdits=x.imageEdits||emptySplit().imageEdits; return x;}
async function restoreImageFromState(){srcImg=null; if(objUrl)URL.revokeObjectURL(objUrl); objUrl=''; if(state.split.imageInfo?.preview){srcImg=await loadImage(state.split.imageInfo.preview).catch(()=>null); return;} const blob=await getImage(state.split.id); if(blob){objUrl=URL.createObjectURL(blob); srcImg=await loadImage(objUrl).catch(()=>null); state.split.imageInfo.preview=await blobToDataURL(blob);}}
async function loadSplit(id){const s=await getSplit(id); if(!s)return; state.split=revive(s); await restoreImageFromState(); goto(1);} 
async function duplicateSplit(id){const s=await getSplit(id); if(!s)return; const c=revive(s); c.id=crypto.randomUUID(); c.createdAt=iso(); c.updatedAt=iso(); c.completed=false; await saveSplit(c); const blob=await getImage(id); if(blob)await saveImage(c.id,blob); await loadHistory(); state.split=c; await restoreImageFromState(); goto(0);} 
async function deleteSplit(id){await store('splits','readwrite',os=>os.delete(id)); await store('images','readwrite',os=>os.delete(id)); await loadHistory(); if(state.split.id===id)resetSplit(false); renderAll();}
async function openDB(){if(dbp)return dbp; dbp=new Promise((res,rej)=>{const req=indexedDB.open(DB,DBV); req.onupgradeneeded=()=>{const db=req.result; if(!db.objectStoreNames.contains('splits')){const s=db.createObjectStore('splits',{keyPath:'id'}); s.createIndex('imageHash','imageHash'); s.createIndex('updatedAt','updatedAt');} if(!db.objectStoreNames.contains('images'))db.createObjectStore('images',{keyPath:'id'}); if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'id'}); if(!db.objectStoreNames.contains('ledgers'))db.createObjectStore('ledgers',{keyPath:'id'});}; req.onsuccess=()=>res(req.result); req.onerror=()=>rej(req.error);}); return dbp;}
async function store(name,mode,fn){const db=await openDB(); return new Promise((res,rej)=>{const tx=db.transaction(name,mode),os=tx.objectStore(name); let out; try{out=fn(os,tx);}catch(e){rej(e);return;} tx.oncomplete=()=>res(out?.result??out); tx.onerror=()=>rej(tx.error||new Error('IndexedDB failed'));});}
async function saveSplit(s){await store('splits','readwrite',os=>os.put(clone(s)));} async function getSplit(id){return store('splits','readonly',os=>os.get(id));} async function loadHistory(){state.history=(await store('splits','readonly',os=>os.getAll())||[]).map(revive).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));}
async function saveSettings(){await store('settings','readwrite',os=>os.put({id:'settings',value:state.settings}));} async function loadSettings(){const s=await store('settings','readonly',os=>os.get('settings')).catch(()=>null); if(s?.value)state.settings={...state.settings,...s.value};}
async function saveLedgers(){await store('ledgers','readwrite',(os)=>{os.clear(); state.ledgers.forEach(l=>os.put({id:l.id,value:l}));});} async function loadLedgers(){const rows=await store('ledgers','readonly',os=>os.getAll()).catch(()=>[]); state.ledgers=(rows||[]).map(r=>r.value);} 
async function saveImage(id,blob){await store('images','readwrite',os=>os.put({id,blob}));} async function getImage(id){const row=await store('images','readonly',os=>os.get(id)); return row?.blob||null;}
async function encryptJSON(payload,pass){const enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),mat=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['encrypt']),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(payload))); return{version:1,salt:b64(salt.buffer),iv:b64(iv.buffer),payload:b64(cipher)};}
async function decryptJSON(data,pass){const enc=new TextEncoder(),mat=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:ub64(data.salt),iterations:150000,hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub64(data.iv)},key,ub64(data.payload)); return JSON.parse(new TextDecoder().decode(plain));}
async function hostRoom(){await ensurePeer(); const code=$('roomCodeInput').value.trim()||`snapsplit-${Math.random().toString(36).slice(2,8).toUpperCase()}`; $('roomCodeInput').value=code; roomCrypto=await roomKey(code,$('roomPassInput').value.trim()); if(peer)peer.destroy(); peer=new PeerAPI.Peer(code); peer.on('open',id=>{refs.roomStatus.textContent=`Hosting room ${id}. Keep this tab open.`; announce('Room hosted.');}); peer.on('connection',c=>{conn=c; c.on('open',()=>syncRoom().catch(console.error)); c.on('close',()=>refs.roomStatus.textContent='Guest disconnected.');}); peer.on('error',e=>refs.roomStatus.textContent=e.message);} 
async function joinRoom(){await ensurePeer(); const code=$('roomCodeInput').value.trim(); if(!code){announce('Enter a room code.');return;} roomCrypto=await roomKey(code,$('roomPassInput').value.trim()); if(peer)peer.destroy(); peer=new PeerAPI.Peer(); peer.on('open',()=>{conn=peer.connect(code); conn.on('open',()=>refs.roomStatus.textContent=`Connected to ${code}.`); conn.on('data',async payload=>{const snap=await roomDecrypt(payload); state.split.receipt=snap.split.receipt; state.split.participants=snap.split.participants; state.split.ui=snap.split.ui||{ack:false}; goto(1); queueSave(); refs.roomStatus.textContent=`Synced from ${code}.`;});}); peer.on('error',e=>refs.roomStatus.textContent=e.message);} 
async function syncRoom(){if(!conn?.open||!roomCrypto){refs.roomStatus.textContent='No active room connection.';return;} const snap={split:{id:state.split.id,receipt:state.split.receipt,participants:state.split.participants,ui:state.split.ui},sentAt:iso()}; conn.send(await roomEncrypt(snap)); refs.roomStatus.textContent='Latest split state sent.';}
async function ensurePeer(){if(PeerAPI)return; await loadScript('https://cdn.jsdelivr.net/npm/peerjs@1.5.4/dist/peerjs.min.js'); PeerAPI=window;}
async function roomKey(code,pass){if(!pass)throw new Error('Passphrase required for encrypted room sync.'); const enc=new TextEncoder(),mat=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:enc.encode(code),iterations:120000,hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['encrypt','decrypt']); return{key};}
async function roomEncrypt(v){const iv=crypto.getRandomValues(new Uint8Array(12)),data=new TextEncoder().encode(JSON.stringify(v)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},roomCrypto.key,data); return{iv:b64(iv.buffer),payload:b64(cipher)};} async function roomDecrypt(v){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub64(v.iv)},roomCrypto.key,ub64(v.payload)); return JSON.parse(new TextDecoder().decode(plain));}
async function loadScript(src){if([...document.scripts].some(s=>s.src===src))return; await new Promise((res,rej)=>{const s=document.createElement('script'); s.src=src; s.onload=res; s.onerror=()=>rej(new Error(`Failed to load ${src}`)); document.head.appendChild(s);});}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf)));} function ub64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0)).buffer;}
async function sha(ab){const h=await crypto.subtle.digest('SHA-256',ab); return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image(); img.onload=()=>res(img); img.onerror=()=>rej(new Error('Could not decode the selected image.')); img.src=src;});}
function blobToDataURL(blob){return new Promise((res,rej)=>{const fr=new FileReader(); fr.onload=()=>res(fr.result); fr.onerror=rej; fr.readAsDataURL(blob);});}
function runDebug(){const out=[]; const test=(name,fn)=>Promise.resolve().then(fn).then(()=>out.push({name,ok:true})).catch(e=>out.push({name,ok:false,error:e.message})); Promise.resolve().then(async()=>{await test('Single-person receipt',()=>{const s=demo(1,false,false); const c=calc(s); assert(c.valid,'Expected valid split'); assert(Object.values(c.people)[0].finalCents===s.receipt.totalCents,'Single person should cover total');}); await test('Multiple participants',()=>{const s=demo(3,true,false); const c=calc(s); assert(c.valid,'Expected valid equal split'); assert(c.settlements.length===2,'Two people should pay payer');}); await test('Shared item',()=>{const s=demo(2,true,false); const c=calc(s); assert(c.people[s.participants[0].id].itemSubtotalCents===650,'Shared item should split in half');}); await test('Weighted split',()=>{const s=demo(2,false,true); const c=calc(s); assert(c.valid,'Weighted split should validate');}); await test('Discounts',()=>{const s=demo(2,true,false); s.receipt.discountsCents=200; s.receipt.totalCents-=200; const c=calc(s); assert(c.totals.discounts===200,'Discount should allocate');}); await test('Tax and tip',()=>{const s=demo(2,true,false); const c=calc(s); assert(c.totals.tax===s.receipt.taxCents&&c.totals.tip===s.receipt.tipCents,'Tax and tip should allocate');}); await test('One-cent remainder',()=>{const a=alloc(1,[{participantId:'a',numerator:1},{participantId:'b',numerator:1}]); assert(a[0].cents+a[1].cents===1,'One cent remainder should allocate');}); await test('Zero-value item',()=>{const s=demo(2,true,false); s.receipt.items.push({...emptyItem(),name:'Comped',assignedParticipantIds:[s.participants[0].id],splitMode:'single'}); const c=calc(s); assert(c.valid,'Zero value item should not break math');}); await test('Negative discount normalization',()=>{const p=parseReceiptText('Diner\nSubtotal 10.00\nDiscount -1.00\nTax 0.90\nTotal 9.90'); assert(p.discountsCents===100,'Discount should normalize');}); await test('Unbalanced receipt',()=>{const s=demo(2,true,false); s.receipt.subtotalCents+=1; s.receipt.discrepancyCents=1; const c=calc(s); assert(!c.valid,'Unbalanced receipt should fail');}); await test('Duplicate receipt hash stable',async()=>{const h=await sha(new TextEncoder().encode('abc').buffer); assert(h.length===64,'SHA-256 expected');}); await test('Trip Ledger settlement',()=>{const summary=ledgerSummary({participants:[{name:'Alice'},{name:'Bob'},{name:'Carla'}],receipts:[{payer:'Alice',totalCents:5000,results:[{name:'Alice',finalCents:0},{name:'Bob',finalCents:2000},{name:'Carla',finalCents:3000}]}],currency:'USD'}); assert(summary.transfers.length===2,'Should simplify to two transfers');}); refs.debugResults.innerHTML=out.map(r=>`<div class="debug-card ${r.ok?'ok':'bad'}"><strong>${r.ok?'PASS':'FAIL'}</strong> · ${esc(r.name)}${r.error?`<div class="muted small">${esc(r.error)}</div>`:''}</div>`).join(''); announce('Developer tests finished.');});}
function demo(count,equal,weighted){const s=emptySplit(); s.receipt.merchant='Demo'; s.receipt.currency='USD'; s.participants=Array.from({length:count},(_,i)=>participant(`P${i+1}`,COLORS[i],i===1&&weighted?.5:1)); s.participants[0].isPayer=true; s.receipt.items=[{...emptyItem(),name:'Burger',unitPriceCents:1300,totalPriceCents:1300,assignedParticipantIds:s.participants.map(p=>p.id).slice(0,equal||weighted?count:1),splitMode:weighted?'weighted':equal?'equal':'single'}]; s.receipt.subtotalCents=1300; s.receipt.taxCents=100; s.receipt.tipCents=200; s.receipt.totalCents=1600; s.receipt.discrepancyCents=0; return s;}
function assert(cond,msg){if(!cond)throw new Error(msg);} 
function registerSW(){if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});} 
window.SnapSplitEngine={calc,alloc,ledgerSummary,parseReceiptText};
})();
